dev

diff --git a/grub-mkpasswd b/grub-mkpasswd
--- a/grub-mkpasswd
+++ b/grub-mkpasswd
@@ -10,6 +10,23 @@ then
     exit 1
 fi
 
+fn_check_command() {
+    hash $1 2> /dev/null
+    
+    if [ $? -eq 1 ]; then
+        echo "command:$1 not found!"
+        echo "please try 'apt install $2'"
+        exit 1
+    fi
+}
+
+## REQUIREMENTS
+set +e
+fn_check_command tee tee
+fn_check_command grub-mkpasswd-pbkdf2 grub-common
+fn_check_command update-grub2 grub-common
+set -e
+
 ## DECLARE VARIABLES
 user_config_file=/etc/grub.d/01_users
 
